# Site Settings
title: ROBOTMAK3RS
email: ambassador@robotmak3rs.com
description: Robot makers from around the world who embrace all LEGO robotic platforms (MINDSTORMS, WeDo and BOOST) to MAKE robots, SHARE our passion and INSPIRE generations to come to be interested in Science Technology Engineering Arts and Mathematics via the joys of "playing" with LEGO.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-121857427-1"

# User Settings
username: ROBOTMAK3RS
user_description: Recognized LEGO Online Community of Robot Experts.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
# github_username: robotmak3rs
facebook_username: /groups/1047713702069822/about/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
